### ISSUE TITLE
Not exist 00135/Outer/Take21 in dataset

### ISSUE THREAD

**Issue by hygenie1228** [eth-ait/4d-dress#4]
Thanks for sharing the great work and dataset.

I am currently checking the benchmark of HumanReconstruction.
https://github.com/eth-ait/4d-dress/blob/baf3e8f0857f7b22996512ba82a55c9530f268ce/dataset/benchmarks.py#L37

However, I cannot find the subject of 00135/Outer/Take21 in your distributed dataset.
Could you check it?
![image](https://github.com/eth-ait/4d-dress/assets/69622221/a62e8ac9-9b29-40c5-a34f-4181a053483a)

**Comment by azuxmioy** [comment]
There should be 8 sequences in total and we compressed them into two separate tar.gz files.
It seems that you missed downloading one of the tar.gz files.

**Comment by hygenie1228** [comment]
I confirmed that it exists in the re-downloaded version.

Thanks for checking!
