### ISSUE TITLE
The Sec.6.2 Clothed Human Reconstruction

### ISSUE THREAD

**Issue by Jun-Pu** [eth-ait/4d-dress#5]
Thanks so much for releasing such a valuable fine-grained 4D dataset!

I would like to know if you are going to release the three experiments mentioned in the 'Clothed Human Reconstruction' section？

We would like to cite and compare our benchmark models with yours without having to re-run the experiments.

Thanks in advance!

Yi

**Comment by Jun-Pu** [comment]
Hi, thx for the prompt reply! The email and another application sent.

**Comment by MoyGcc** [comment]
Yes, the video-based human reconstruction task always uses the "0004" camera which is the front-facing camera in the released camera views.
